// Comprehensive Expansion for TripMate Destination Places
// Expands Hyderabad, Bengaluru, Kerala, Bangkok, Bali, London, New York, Rome, Kuala Lumpur, Vizag, Switzerland, New Zealand, Sydney to 16 curated places each.

const EXPANDED = {
  hyderabad: [
    {
      id: "hyd-charminar",
      name: "Charminar & Laad Bazaar",
      category: "Culture",
      rating: 4.8,
      price: 50,
      location: "Old City, Hyderabad",
      description: "Iconic 1591 monument with four grand minarets, surrounded by colorful lacquer bangle stalls and pearl merchants.",
      tags: ["Culture", "Shopping", "Photography"],
      image: "https://images.unsplash.com/photo-1605007493699-ce65834f8a00?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 17:30",
      bestTimeToVisit: "Morning & Sunset"
    },
    {
      id: "hyd-golconda",
      name: "Golconda Fort & Acoustic Echo Walk",
      category: "History",
      rating: 4.7,
      price: 150,
      location: "Ibrahim Bagh",
      description: "Magnificent fortress renowned for its acoustic engineering, royal palaces, diamond vaults, and evening sound-and-light show.",
      tags: ["History", "Adventure", "Photography"],
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 18:00",
      bestTimeToVisit: "Late Afternoon"
    },
    {
      id: "hyd-ramoji",
      name: "Ramoji Film City Grand Studio",
      category: "Adventure",
      rating: 4.6,
      price: 1250,
      location: "Hayathnagar",
      description: "Guinness World Record holding film complex with stunt shows, movie sets, gardens, and adventure rides.",
      tags: ["Adventure", "Culture", "Photography"],
      image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 17:30",
      bestTimeToVisit: "Full Day"
    },
    {
      id: "hyd-chowmahalla",
      name: "Chowmahalla Palace & Vintage Cars",
      category: "Culture",
      rating: 4.7,
      price: 100,
      location: "Motigallu, Khilwat",
      description: "Opulent seat of the Asaf Jahi dynasty featuring vintage Rolls Royce cars, Belgian crystal chandeliers, and lush courtyards.",
      tags: ["Culture", "History", "Photography"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "hyd-biryani-paradise",
      name: "Authentic Hyderabadi Dum Biryani Feast",
      category: "Food",
      rating: 4.9,
      price: 650,
      location: "Banjara Hills / Abids",
      description: "Tender slow-cooked spiced mutton layered with fragrant basmati rice, served with mirchi ka salan and dahi chutney.",
      tags: ["Food", "Culture"],
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
      openingHours: "12:00 - 23:30",
      bestTimeToVisit: "Lunch & Dinner"
    },
    {
      id: "hyd-hussain-sagar",
      name: "Hussain Sagar Lake & Buddha Statue Boat Ride",
      category: "Nature",
      rating: 4.5,
      price: 120,
      location: "Necklace Road",
      description: "Heart-shaped urban lake with speedboat rides to the world's tallest monolithic Buddha statue and breezy promenade.",
      tags: ["Nature", "Relaxed", "Photography"],
      image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 22:00",
      bestTimeToVisit: "Sunset & Evening"
    },
    {
      id: "hyd-salar-jung",
      name: "Salar Jung Museum & Musical Clock",
      category: "Culture",
      rating: 4.8,
      price: 50,
      location: "Darulshifa",
      description: "One of the largest individual art collections in the world, famous for the veiled Rebecca marble and 19th-century mechanical clock.",
      tags: ["Culture", "History", "Art"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "hyd-qutb-shahi",
      name: "Qutb Shahi Tombs & Royal Gardens",
      category: "History",
      rating: 4.7,
      price: 40,
      location: "Tolichowki",
      description: "Grand domed mausoleums blending Persian, Pashtun, and Hindu architecture set in tranquil Ibrahim Bagh landscaped gardens.",
      tags: ["History", "Architecture", "Photography"],
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:30 - 16:30",
      bestTimeToVisit: "Late Afternoon"
    },
    {
      id: "hyd-shilparamam",
      name: "Shilparamam Arts & Crafts Village",
      category: "Shopping",
      rating: 4.6,
      price: 60,
      location: "HITEC City, Madhapur",
      description: "Rural heritage crafts village with terracotta artisans, handloom silks, boating, and open-air ethnic performances.",
      tags: ["Shopping", "Culture", "Handicrafts"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:30 - 20:30",
      bestTimeToVisit: "Evening"
    },
    {
      id: "hyd-birla-mandir",
      name: "Birla Mandir & Naubat Pahad Sunset View",
      category: "Sightseeing",
      rating: 4.8,
      price: 0,
      location: "Hill Fort Road",
      description: "Pristine white Rajasthani marble temple perched atop a 280-foot hill offering sweeping panoramic skyline views.",
      tags: ["Sightseeing", "Culture", "Photography"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 12:00, 15:00 - 21:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "hyd-zoo-park",
      name: "Nehru Zoological Park & Lion Safari",
      category: "Nature",
      rating: 4.5,
      price: 80,
      location: "Bahadurpura",
      description: "Expansive 380-acre botanical and wildlife sanctuary featuring safari vans, nocturnal animal house, and serene lakes.",
      tags: ["Nature", "Wildlife", "Family"],
      image: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:30 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "hyd-nimrah-cafe",
      name: "Nimrah Cafe Irani Chai & Osmania Biscuits",
      category: "Food",
      rating: 4.9,
      price: 80,
      location: "Charminar Road",
      description: "Legendary heritage tea stall brewing spiced, milky Irani Chai paired with warm melt-in-the-mouth salted Osmania biscuits.",
      tags: ["Food", "Local Street Eats", "Iconic"],
      image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
      openingHours: "04:00 - 23:00",
      bestTimeToVisit: "Morning & Late Night"
    },
    {
      id: "hyd-durgam-cheruvu",
      name: "Durgam Cheruvu Cable Bridge & Waterfront",
      category: "Sightseeing",
      rating: 4.7,
      price: 0,
      location: "Jubilee Hills",
      description: "Stunning illuminated suspension cable bridge over the Secret Lake, featuring a floating musical fountain and modern cafes.",
      tags: ["Sightseeing", "Architecture", "Nightlife"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Night"
    },
    {
      id: "hyd-falaknuma",
      name: "Taj Falaknuma Palace Royal Tea Walk",
      category: "Culture",
      rating: 4.9,
      price: 2500,
      location: "Engine Bowli, Falaknuma",
      description: "Scorpion-shaped Italian marble palace 2,000 feet above the city, once home to the Nizam, featuring royal horse carriage arrivals.",
      tags: ["Culture", "Luxury", "History"],
      image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
      openingHours: "15:30 - 18:30",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "hyd-mozamjahi",
      name: "Mozamjahi Heritage Market & Famous Ice Cream",
      category: "Food",
      rating: 4.6,
      price: 150,
      location: "Abids",
      description: "Granite heritage clock tower bazaar established in 1935, celebrated for handmade seasonal fruit ice creams (Mango & Sapota).",
      tags: ["Food", "Heritage", "Dessert"],
      image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 23:00",
      bestTimeToVisit: "Evening"
    },
    {
      id: "hyd-kbr-park",
      name: "KBR National Park Jubilee Hills Trail",
      category: "Nature",
      rating: 4.7,
      price: 40,
      location: "Jubilee Hills",
      description: "Pristine urban rainforest nature trail surrounded by boulder rock formations, peacocks, and lush native flora.",
      tags: ["Nature", "Trek", "Relaxed"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "05:30 - 09:30, 16:30 - 18:30",
      bestTimeToVisit: "Early Morning"
    }
  ],

  bengaluru: [
    {
      id: "blr-lalbagh",
      name: "Lalbagh Botanical Garden & Glass House",
      category: "Nature",
      rating: 4.8,
      price: 30,
      location: "Mavalli",
      description: "240-acre botanical haven dating to Hyder Ali, featuring London Crystal Palace-inspired glass pavilion and centuries-old trees.",
      tags: ["Nature", "Photography", "Relaxed"],
      image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 19:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "blr-palace",
      name: "Bangalore Palace & Tudor Towers",
      category: "History",
      rating: 4.6,
      price: 250,
      location: "Vasanth Nagar",
      description: "19th-century royal palace resembling England's Windsor Castle, featuring fortified towers, woodcarvings, and vintage paintings.",
      tags: ["History", "Culture", "Architecture"],
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:30",
      bestTimeToVisit: "Late Morning"
    },
    {
      id: "blr-cubbon",
      name: "Cubbon Park & Bamboo Forest Stroll",
      category: "Nature",
      rating: 4.7,
      price: 0,
      location: "Kasturba Road",
      description: "Sprawling 300-acre green lung in central Bangalore with red Gothic libraries, walking trails, and canopy trees.",
      tags: ["Nature", "Relaxed", "Walks"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 20:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "blr-vidhana",
      name: "Vidhana Soudha & High Court View",
      category: "Sightseeing",
      rating: 4.6,
      price: 0,
      location: "Ambedkar Veedhi",
      description: "Imposing Neo-Dravidian granite legislative assembly palace, brilliantly illuminated with golden floodlights on Sunday evenings.",
      tags: ["Sightseeing", "Architecture", "Night View"],
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
      openingHours: "External Viewing",
      bestTimeToVisit: "Evening Illumination"
    },
    {
      id: "blr-dosa-vidyarthi",
      name: "Vidyarthi Bhavan Crispy Masala Dosa",
      category: "Food",
      rating: 4.9,
      price: 180,
      location: "Gandhi Bazaar, Basavanagudi",
      description: "Historic 1943 heritage tiffin room serving thick, golden-crispy ghee masala dosas served with unlimited coconut chutney.",
      tags: ["Food", "Iconic", "Breakfast"],
      image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:30 - 12:00, 14:00 - 20:00",
      bestTimeToVisit: "Morning Breakfast"
    },
    {
      id: "blr-bannerghatta",
      name: "Bannerghatta Biological Park & Bear Safari",
      category: "Adventure",
      rating: 4.5,
      price: 350,
      location: "Bannerghatta",
      description: "Vast conservation park with tiger & sloth bear bus safari, butterfly conservatory dome, and zoo.",
      tags: ["Adventure", "Wildlife", "Nature"],
      image: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:30 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "blr-commercial-st",
      name: "Commercial Street Silk & Artisan Bazaars",
      category: "Shopping",
      rating: 4.6,
      price: 0,
      location: "Tasker Town, Shivajinagar",
      description: "Vibrant shopping grid renowned for Mysore pure silks, silver trinkets, bespoke tailoring, and hot roadside snacks.",
      tags: ["Shopping", "Culture", "Fashion"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:30 - 21:00",
      bestTimeToVisit: "Afternoon & Evening"
    },
    {
      id: "blr-tipu-palace",
      name: "Tipu Sultan's Summer Palace & Teak Pillars",
      category: "History",
      rating: 4.5,
      price: 25,
      location: "Chamrajpet",
      description: "Two-story 1791 teakwood summer retreat adorned with floral motifs, carved arches, and historical Mysore war artifacts.",
      tags: ["History", "Architecture"],
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:30 - 17:30",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "blr-church-st",
      name: "Church Street Bookstores & Cozy Cafes",
      category: "Culture",
      rating: 4.8,
      price: 0,
      location: "Church Street, Ashok Nagar",
      description: "Pedestrianized cobblestone avenue buzzing with legendary Blossom Book House, indie art galleries, and craft coffee bars.",
      tags: ["Culture", "Nightlife", "Walks"],
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 23:00",
      bestTimeToVisit: "Evening"
    },
    {
      id: "blr-iskcon",
      name: "ISKCON Temple Rajajinagar Grand Complex",
      category: "Culture",
      rating: 4.8,
      price: 0,
      location: "Hare Krishna Hill, Rajajinagar",
      description: "Magnificent hill shrine with intricate gold-plated flagstaff, spiritual multimedia pavilions, and delicious temple prasadam.",
      tags: ["Culture", "Architecture", "Spiritual"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:15 - 13:00, 16:15 - 20:30",
      bestTimeToVisit: "Evening Aarti"
    },
    {
      id: "blr-hal-aero",
      name: "HAL Heritage Centre & Aerospace Aviation Park",
      category: "Sightseeing",
      rating: 4.6,
      price: 80,
      location: "Old Airport Road",
      description: "India's premier aviation museum displaying indigenous fighter jets, helicopters, radar towers, and flight simulators.",
      tags: ["Sightseeing", "History", "Family"],
      image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 16:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "blr-toit-brew",
      name: "Toit Indiranagar Craft Brews & Woodfire Eats",
      category: "Food",
      rating: 4.8,
      price: 900,
      location: "100ft Road, Indiranagar",
      description: "Pioneering microbrewery with British pub vibes serving signature Tint-In-Wit Belgian ales and gourmet sourdough pizzas.",
      tags: ["Food", "Nightlife", "Iconic"],
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
      openingHours: "12:00 - 00:30",
      bestTimeToVisit: "Evening & Dinner"
    },
    {
      id: "blr-ulsoor-lake",
      name: "Ulsoor Lake Boating & Sunset Island Walk",
      category: "Nature",
      rating: 4.5,
      price: 60,
      location: "Ulsoor, Halasuru",
      description: "Historic 120-acre lake dotted with verdant islands, pedal boat facilities, and perimeter jogging paths under weeping figs.",
      tags: ["Nature", "Boating", "Sunset"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 20:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "blr-ngma",
      name: "National Gallery of Modern Art (NGMA)",
      category: "Culture",
      rating: 4.7,
      price: 40,
      location: "Palace Road, Vasanth Nagar",
      description: "Colonial-era Manikyavelu heritage mansion surrounded by mirror reflection pools and modern Indian art retrospectives.",
      tags: ["Culture", "Art", "Heritage"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "blr-vv-puram",
      name: "VV Puram Thindi Beedi Street Food Trail",
      category: "Food",
      rating: 4.8,
      price: 250,
      location: "Old Brahmin Street, Sajjan Rao Circle",
      description: "Legendary nocturnal vegetarian street culinary lane serving hot paddus, buttery congress bun, and seasonal rasgulla chaat.",
      tags: ["Food", "Street Eats", "Culture"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "18:00 - 23:30",
      bestTimeToVisit: "Night Food Trail"
    },
    {
      id: "blr-bull-temple",
      name: "Bull Temple & Basavanagudi Heritage Quarter",
      category: "Culture",
      rating: 4.6,
      price: 0,
      location: "Bull Temple Road",
      description: "Monolithic 16th-century granite Nandi bull statue carved from a single boulder, center of the annual groundnut fair.",
      tags: ["Culture", "History", "Heritage"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 20:00",
      bestTimeToVisit: "Morning"
    }
  ],

  kerala: [
    {
      id: "ker-alleppey",
      name: "Alleppey Backwater Houseboat Cruise",
      category: "Nature",
      rating: 4.9,
      price: 1500,
      location: "Punnamada, Alappuzha",
      description: "Gliding through palm-fringed canals and tranquil lagoons on a traditional thatched-roof Kettuvallam houseboat.",
      tags: ["Nature", "Relaxed", "Food"],
      image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
      openingHours: "11:30 - 17:30",
      bestTimeToVisit: "Day Cruise / Sunset"
    },
    {
      id: "ker-munnar",
      name: "Munnar Tea Plantations & Echo Point",
      category: "Nature",
      rating: 4.8,
      price: 100,
      location: "Idukki District",
      description: "Rolling carpet of emerald tea gardens 1,600m above sea level, misty mountain trails, and rare Neelakurinji flora.",
      tags: ["Nature", "Adventure", "Photography"],
      image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 18:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ker-fort-kochi",
      name: "Fort Kochi Chinese Fishing Nets & Pier",
      category: "Sightseeing",
      rating: 4.7,
      price: 0,
      location: "Fort Kochi Beach",
      description: "Centuries-old cantilevered Chinese fishing nets silhouetted against Arabian Sea sunsets, lined with colonial cafes.",
      tags: ["Sightseeing", "History", "Sunset"],
      image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "ker-jew-town",
      name: "Mattancherry Dutch Palace & Jewish Synagogue",
      category: "History",
      rating: 4.6,
      price: 50,
      location: "Jew Town, Mattancherry",
      description: "1568 Paradesi Synagogue with Belgian chandeliers and hand-painted blue Cantonese willow porcelain tiles.",
      tags: ["History", "Culture", "Antiques"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ker-periyar",
      name: "Periyar Wildlife Sanctuary Lake Boat Safari",
      category: "Adventure",
      rating: 4.7,
      price: 450,
      location: "Thekkady",
      description: "Scenic boat ride along an artificial highland reservoir observing wild elephant herds, sambar deer, and otters.",
      tags: ["Adventure", "Wildlife", "Nature"],
      image: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 16:30",
      bestTimeToVisit: "Morning Safari"
    },
    {
      id: "ker-varkala",
      name: "Varkala Red Cliff & Papanasam Beach",
      category: "Beach",
      rating: 4.8,
      price: 0,
      location: "Varkala Cliff Promenade",
      description: "Dramatic geological laterite cliffs rising directly above pristine sandy beaches, lined with yoga retreats and seafood bistros.",
      tags: ["Beach", "Relaxed", "Sunset"],
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "ker-sadhya",
      name: "Traditional Kerala Sadhya on Banana Leaf",
      category: "Food",
      rating: 4.9,
      price: 350,
      location: "Paragon / BTH Sarovaram",
      description: "Sumptuous vegetarian grand feast comprising 26 distinct dishes, avial, sambar, payasam, and red matta rice.",
      tags: ["Food", "Culture", "Authentic"],
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
      openingHours: "12:00 - 15:30",
      bestTimeToVisit: "Lunch"
    },
    {
      id: "ker-athirappilly",
      name: "Athirappilly Waterfalls Rainforest Walk",
      category: "Nature",
      rating: 4.8,
      price: 50,
      location: "Chalakudy, Thrissur",
      description: "Majestic 80-foot wide cascading waterfall often heralded as the Niagara of India, framed by Sholayar rainforests.",
      tags: ["Nature", "Adventure", "Photography"],
      image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ker-kathakali",
      name: "Kathakali Performance & Green Room Makeup",
      category: "Culture",
      rating: 4.8,
      price: 350,
      location: "Kerala Kathakali Centre, Fort Kochi",
      description: "Classical theatrical dance drama showcasing facial makeup transformations, mudras, and epic mythological storytelling.",
      tags: ["Culture", "Art", "Nightlife"],
      image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80",
      openingHours: "17:00 - 20:00",
      bestTimeToVisit: "Evening"
    },
    {
      id: "ker-marari",
      name: "Marari Serene Beach & Fishermen Village",
      category: "Beach",
      rating: 4.7,
      price: 0,
      location: "Mararikulam",
      description: "Quiet white-sand beach lined with coconut groves, thatched shacks, and authentic village boat launches.",
      tags: ["Beach", "Nature", "Relaxed"],
      image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Late Afternoon"
    },
    {
      id: "ker-wayanad-caves",
      name: "Wayanad Edakkal Prehistoric Caves Trek",
      category: "Adventure",
      rating: 4.6,
      price: 80,
      location: "Nenmeni, Wayanad",
      description: "Neolithic rock-cut engravings and petroglyphs dated to 6,000 BCE reached via an adventurous uphill bamboo trek.",
      tags: ["Adventure", "History", "Trek"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 16:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ker-spice-walk",
      name: "Kumily Spice Plantation Aroma Trail",
      category: "Nature",
      rating: 4.7,
      price: 150,
      location: "Thekkady",
      description: "Sensory guided tour amidst cardamom pods, black peppercorns, cinnamon barks, nutmeg trees, and natural vanilla vines.",
      tags: ["Nature", "Shopping", "Educational"],
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:30 - 17:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ker-kovalam",
      name: "Kovalam Lighthouse Beach & Ayurvedic Spa",
      category: "Beach",
      rating: 4.7,
      price: 20,
      location: "Kovalam, Thiruvananthapuram",
      description: "Crescent beach dominated by a striped 35-meter red-and-white stone lighthouse, famed for herbal Ayurvedic massages.",
      tags: ["Beach", "Wellness", "Sightseeing"],
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 18:00 (Lighthouse)",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "ker-kumarakom",
      name: "Kumarakom Bird Sanctuary & Vembanad Walk",
      category: "Nature",
      rating: 4.6,
      price: 100,
      location: "Kavanattinkara",
      description: "14-acre wetland paradise on the banks of Lake Vembanad sheltering Siberian cranes, flycatchers, and teals.",
      tags: ["Nature", "Birding", "Relaxed"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 18:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "ker-paragon-food",
      name: "Calicut Paragon Malabar Dum Biryani & Seafood",
      category: "Food",
      rating: 4.9,
      price: 450,
      location: "CH Flyover / Kochi Branch",
      description: "World-renowned restaurant celebrated for aromatic kaima rice biryani, karimeen pollichathu (pearl spot in banana leaf), and coin parottas.",
      tags: ["Food", "Seafood", "Iconic"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "12:00 - 23:00",
      bestTimeToVisit: "Dinner"
    },
    {
      id: "ker-bekal",
      name: "Bekal Fort Ocean Ramparts & Coastal View",
      category: "History",
      rating: 4.7,
      price: 25,
      location: "Kasaragod",
      description: "Keyhole-shaped 1650 coastal citadel jutting into the sea with panoramic observation towers and water tanks.",
      tags: ["History", "Architecture", "Photography"],
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 17:30",
      bestTimeToVisit: "Late Afternoon"
    }
  ],

  bangkok: [
    {
      id: "bkk-grand-palace",
      name: "Grand Palace & Emerald Buddha Temple",
      category: "History",
      rating: 4.8,
      price: 500,
      location: "Na Phra Lan Rd, Phra Borom Maha Ratchawang",
      description: "Gilded complex of royal residences and the sacred Wat Phra Kaew housing the revered Emerald Buddha carved from jasper.",
      tags: ["History", "Culture", "Architecture"],
      image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:30 - 15:30",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "bkk-wat-arun",
      name: "Wat Arun (Temple of Dawn) Riverfront",
      category: "Culture",
      rating: 4.8,
      price: 100,
      location: "Bangkok Yai, Chao Phraya West Bank",
      description: "Dramatic riverside Khmer-style prang spires decorated with millions of pieces of colorful Chinese porcelain mosaics.",
      tags: ["Culture", "Photography", "Sunset"],
      image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "bkk-wat-pho",
      name: "Wat Pho & Reclining Buddha Sanctuary",
      category: "Culture",
      rating: 4.7,
      price: 200,
      location: "Sanam Chai Rd, Phra Nakhon",
      description: "Famous for the monumental 46-meter gold-plated reclining Buddha with mother-of-pearl feet, and birth place of Thai massage.",
      tags: ["Culture", "History", "Wellness"],
      image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bkk-chatuchak",
      name: "Chatuchak Weekend Market & Street Stalls",
      category: "Shopping",
      rating: 4.7,
      price: 0,
      location: "Kamphaeng Phet 2 Rd, Chatuchak",
      description: "World's largest outdoor weekend market containing over 15,000 stalls selling vintage clothing, handcrafted ceramics, and snacks.",
      tags: ["Shopping", "Food", "Vibrant"],
      image: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 18:00 (Sat-Sun)",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bkk-river-cruise",
      name: "Chao Phraya Express Longtail Boat Cruise",
      category: "Sightseeing",
      rating: 4.6,
      price: 150,
      location: "Sathorn Pier",
      description: "Cruising the River of Kings past glittering temples, wooden stilt houses along Thonburi canals, and luxury river hotels.",
      tags: ["Sightseeing", "Boating", "Iconic"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 19:30",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "bkk-chinatown-food",
      name: "Yaowarat Chinatown Night Street Food Trail",
      category: "Food",
      rating: 4.9,
      price: 300,
      location: "Yaowarat Road, Samphanthawong",
      description: "Neon-drenched street food culinary paradise famous for toasted buns, crispy oyster omelets, crab fried rice, and dim sum.",
      tags: ["Food", "Nightlife", "Street Eats"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "18:00 - 01:00",
      bestTimeToVisit: "Night Food Trail"
    },
    {
      id: "bkk-lumpini",
      name: "Lumpini Park Monitor Lizards & Paddle Boating",
      category: "Nature",
      rating: 4.6,
      price: 0,
      location: "Rama IV Rd, Pathum Wan",
      description: "Tranquil green oasis amidst skyscrapers where water monitor lizards roam freely around artificial lakes and jogging tracks.",
      tags: ["Nature", "Wildlife", "Relaxed"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "04:30 - 22:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "bkk-jim-thompson",
      name: "Jim Thompson House & Tropical Silk Garden",
      category: "Culture",
      rating: 4.7,
      price: 200,
      location: "Kasemsan 2 Alley, Pathum Wan",
      description: "Traditional Thai-style teakwood house complex surrounded by a jungle garden, housing Asian antiques and handwoven silk looms.",
      tags: ["Culture", "History", "Architecture"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 18:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "bkk-iconsiam",
      name: "ICONSIAM SookSiam Indoor Floating Market",
      category: "Shopping",
      rating: 4.8,
      price: 0,
      location: "Charoen Nakhon Rd, Khlong San",
      description: "Futuristic luxury mega-mall featuring an air-conditioned recreation of Thailand's 77 provinces with authentic street eats.",
      tags: ["Shopping", "Food", "Modern"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 22:00",
      bestTimeToVisit: "Afternoon & Evening"
    },
    {
      id: "bkk-golden-mount",
      name: "Wat Saket (Golden Mount) 360 Panorama",
      category: "Sightseeing",
      rating: 4.7,
      price: 50,
      location: "Pom Prap Sattru Phai",
      description: "Sacred artificial hill crowned with a gleaming golden stupa reached via 344 spiral steps flanked by prayer bells and mist.",
      tags: ["Sightseeing", "Culture", "Panoramic"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 19:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "bkk-thipsamai",
      name: "Thip Samai Legendary Pad Thai & Fresh Juice",
      category: "Food",
      rating: 4.8,
      price: 180,
      location: "Maha Chai Rd, Samran Rat",
      description: "Historic establishment revered since 1966 for thin egg crepe-wrapped Superb Pad Thai stir-fried over screaming charcoal woks.",
      tags: ["Food", "Iconic", "Culinary"],
      image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80",
      openingHours: "17:00 - 00:00",
      bestTimeToVisit: "Dinner"
    },
    {
      id: "bkk-floating-market",
      name: "Damnoen Saduak Traditional Floating Market",
      category: "Culture",
      rating: 4.5,
      price: 300,
      location: "Ratchaburi Outskirts",
      description: "Iconic wooden paddle boat market where local women wearing straw hats sell tropical mangoes, coconut ice cream, and noodles.",
      tags: ["Culture", "Shopping", "Adventure"],
      image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 12:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "bkk-lebua-skybar",
      name: "Sky Bar at Lebua Tower High-Altitude Deck",
      category: "Sightseeing",
      rating: 4.7,
      price: 800,
      location: "Silom Rd, Bang Rak",
      description: "One of the highest open-air rooftop bars in the world on the 64th floor offering dizzying views of Bangkok's neon skyline.",
      tags: ["Sightseeing", "Nightlife", "Luxury"],
      image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
      openingHours: "18:00 - 01:00",
      bestTimeToVisit: "Night Skyline"
    },
    {
      id: "bkk-asiatique",
      name: "Asiatique The Riverfront Night Bazaar",
      category: "Shopping",
      rating: 4.6,
      price: 0,
      location: "Charoen Krung Rd, Wat Phraya Krai",
      description: "Open-air riverfront mall in restored colonial docks featuring an illuminated giant Ferris wheel, cabaret, and boutique shops.",
      tags: ["Shopping", "Nightlife", "Entertainment"],
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      openingHours: "17:00 - 00:00",
      bestTimeToVisit: "Evening"
    },
    {
      id: "bkk-erawan-shrine",
      name: "Erawan Shrine & Traditional Dancers",
      category: "Culture",
      rating: 4.7,
      price: 0,
      location: "Ratchaprasong Intersection",
      description: "Atmospheric street corner shrine to Phra Phrom (Brahma) enveloped in incense smoke and live performances by traditional Thai dancers.",
      tags: ["Culture", "Spiritual", "Sightseeing"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 22:00",
      bestTimeToVisit: "Evening"
    },
    {
      id: "bkk-sea-life",
      name: "SEA LIFE Bangkok Ocean World Aquarium",
      category: "Adventure",
      rating: 4.6,
      price: 900,
      location: "Siam Paragon B1-B2",
      description: "One of Southeast Asia's largest underground oceanariums with a 270-degree glass tunnel, sand tiger sharks, and gentoo penguins.",
      tags: ["Adventure", "Family", "Marine"],
      image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 20:00",
      bestTimeToVisit: "Afternoon"
    }
  ],

  bali: [
    {
      id: "bali-uluwatu",
      name: "Uluwatu Cliff Temple & Kecak Fire Dance",
      category: "Culture",
      rating: 4.9,
      price: 150,
      location: "Pecatu, South Kuta",
      description: "Ancient sea temple perched on a 70-meter dramatic limestone cliff overlooking Indian Ocean surf, famed for hypnotic sunset Kecak chants.",
      tags: ["Culture", "Sunset", "Performance"],
      image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 19:00",
      bestTimeToVisit: "Sunset Dance Show"
    },
    {
      id: "bali-tegallalang",
      name: "Tegallalang Rice Terraces & Giant Jungle Swing",
      category: "Nature",
      rating: 4.8,
      price: 50,
      location: "Ubud, Gianyar",
      description: "Iconic emerald green tiered rice paddies utilizing the ancient Subak irrigation system, featuring soaring jungle swings.",
      tags: ["Nature", "Adventure", "Photography"],
      image: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:00",
      bestTimeToVisit: "Morning Light"
    },
    {
      id: "bali-tanah-lot",
      name: "Tanah Lot Ocean Rock Temple at Sunset",
      category: "Sightseeing",
      rating: 4.7,
      price: 60,
      location: "Beraban, Tabanan",
      description: "Ancient Hindu pilgrimage shrine perched atop an offshore wave-carved rock islet, accessible on foot only during low tide.",
      tags: ["Sightseeing", "Culture", "Sunset"],
      image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 19:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "bali-monkey-forest",
      name: "Sacred Monkey Forest Sanctuary Ubud",
      category: "Nature",
      rating: 4.6,
      price: 80,
      location: "Padangtegal, Ubud",
      description: "Mystical moss-covered jungle sanctuary with sacred bathing temples and hundreds of free-roaming Balinese long-tailed macaques.",
      tags: ["Nature", "Wildlife", "Culture"],
      image: "https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 18:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bali-batur-trek",
      name: "Mount Batur Sunrise Volcano Trek",
      category: "Adventure",
      rating: 4.8,
      price: 650,
      location: "Kintamani, Bangli",
      description: "Early morning hike up an active 1,717m volcanic caldera to watch dawn break over Lake Batur while eating steam-cooked eggs.",
      tags: ["Adventure", "Trek", "Sunrise"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "03:30 - 09:00 Trek",
      bestTimeToVisit: "Dawn Sunrise"
    },
    {
      id: "bali-seminyak-beach",
      name: "Seminyak Beach Shacks & Sunset Loungers",
      category: "Beach",
      rating: 4.7,
      price: 0,
      location: "Seminyak, Badung",
      description: "Golden sand beach with colorful beanbags, live acoustic guitarists, world-class beach clubs, and crashing surf breaks.",
      tags: ["Beach", "Relaxed", "Nightlife"],
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset & Evening"
    },
    {
      id: "bali-jimbaran-seafood",
      name: "Jimbaran Bay Candlelight Grilled Seafood",
      category: "Food",
      rating: 4.8,
      price: 800,
      location: "Jimbaran Beach",
      description: "Fresh red snapper, king prawns, and calamari grilled over coconut husks with spicy sambal matah right on the wave edge.",
      tags: ["Food", "Seafood", "Romantic"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "16:00 - 23:00",
      bestTimeToVisit: "Sunset Dinner"
    },
    {
      id: "bali-tirta-empul",
      name: "Tirta Empul Holy Water Temple Purification",
      category: "Culture",
      rating: 4.8,
      price: 50,
      location: "Manukaya, Tampaksiring",
      description: "10th-century water temple fed by natural springs where pilgrims undergo spiritual purification under 30 sacred stone spouts.",
      tags: ["Culture", "Spiritual", "Heritage"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bali-nusa-penida",
      name: "Nusa Penida Kelingking 'T-Rex' Cliff Day Tour",
      category: "Adventure",
      rating: 4.9,
      price: 900,
      location: "Nusa Penida Island",
      description: "Mind-blowing limestone headland shaped like a Tyrannosaurus Rex overlooking turquoise seas and secluded white sand beach.",
      tags: ["Adventure", "Island", "Photography"],
      image: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80",
      openingHours: "Full Day Excursion",
      bestTimeToVisit: "Day Tour"
    },
    {
      id: "bali-ubud-art-market",
      name: "Ubud Traditional Art Market & Batik Workshops",
      category: "Shopping",
      rating: 4.6,
      price: 0,
      location: "Jalan Raya Ubud",
      description: "Vibrant bazaar opposite the Royal Palace selling handwoven rattan bags, silk sarongs, wooden tiki statues, and paintings.",
      tags: ["Shopping", "Culture", "Handicrafts"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bali-campuhan-ridge",
      name: "Campuhan Ridge Scenic Green Valley Walk",
      category: "Nature",
      rating: 4.7,
      price: 0,
      location: "Sayan, Ubud",
      description: "Lush undulating ridge walk between the Sungai Cerik and Wos rivers with panoramic views of elephant grass hills and ravines.",
      tags: ["Nature", "Trek", "Relaxed"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 19:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "bali-tegenungan",
      name: "Tegenungan Waterfall & Jungle River Club",
      category: "Nature",
      rating: 4.5,
      price: 40,
      location: "Kemenuh, Sukawati",
      description: "Thundering lowland cascade surrounded by lush tropical greenery, natural wading pools, and cliffside lookouts.",
      tags: ["Nature", "Waterfalls", "Swimming"],
      image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:30 - 18:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bali-besakih",
      name: "Besakih Mother Temple on Mount Agung",
      category: "History",
      rating: 4.7,
      price: 60,
      location: "Besakih, Karangasem",
      description: "Most sacred temple in Bali, a terraced complex of 23 separate temples clinging to the volcanic slope of Mount Agung.",
      tags: ["History", "Culture", "Spiritual"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "bali-sanur-beach",
      name: "Sanur Sunrise Boardwalk & Jukung Sailboats",
      category: "Beach",
      rating: 4.6,
      price: 0,
      location: "Sanur, Denpasar",
      description: "Peaceful 5km seaside paved promenade with calm shallow waters, outrigger fishing canoes, and breezy morning breakfast cafes.",
      tags: ["Beach", "Relaxed", "Sunrise"],
      image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunrise"
    },
    {
      id: "bali-potato-head",
      name: "Potato Head Beach Club & Sustainable Design",
      category: "Food",
      rating: 4.8,
      price: 700,
      location: "Petitenget, Seminyak",
      description: "Architectural masterpiece built from 50,000 antique teak shutters featuring an infinity pool bar, farm-to-table cuisine, and DJ beats.",
      tags: ["Food", "Nightlife", "Architecture"],
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 02:00",
      bestTimeToVisit: "Late Afternoon & Night"
    },
    {
      id: "bali-tirta-gangga",
      name: "Tirta Gangga Royal Water Palace & Giant Koi",
      category: "Sightseeing",
      rating: 4.8,
      price: 50,
      location: "Ababi, Karangasem",
      description: "Former royal palace featuring stepped fountain pools, guardian demon stone statues, and stepping stones across lotus ponds.",
      tags: ["Sightseeing", "Heritage", "Photography"],
      image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 18:00",
      bestTimeToVisit: "Morning"
    }
  ],

  london: [
    {
      id: "ldn-tower",
      name: "Tower of London & Crown Jewels Exhibition",
      category: "History",
      rating: 4.8,
      price: 3300,
      location: "Tower Hill, EC3N 4AB",
      description: "Historic fortress and UNESCO palace guarded by Yeoman Warders (Beefeaters), housing the priceless British Crown Jewels and royal armory.",
      tags: ["History", "Royalty", "Iconic"],
      image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 17:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ldn-big-ben",
      name: "Big Ben & Palace of Westminster Riverside Walk",
      category: "Sightseeing",
      rating: 4.9,
      price: 0,
      location: "Westminster, SW1A 0AA",
      description: "Neo-Gothic Victorian clock tower and parliament buildings along the Thames, stunning when viewed from Westminster Bridge.",
      tags: ["Sightseeing", "Architecture", "Photography"],
      image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours (External)",
      bestTimeToVisit: "Sunset & Night Illumination"
    },
    {
      id: "ldn-british-museum",
      name: "British Museum & Great Court Glass Roof",
      category: "Culture",
      rating: 4.8,
      price: 0,
      location: "Great Russell St, Bloomsbury",
      description: "World-class treasury of human history, art, and culture housing the Rosetta Stone, Parthenon Sculptures, and Egyptian mummies.",
      tags: ["Culture", "History", "Free Entry"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Late Morning"
    },
    {
      id: "ldn-london-eye",
      name: "London Eye Thames Panoramic Flight",
      category: "Sightseeing",
      rating: 4.6,
      price: 3500,
      location: "Riverside Building, County Hall",
      description: "135-meter cantilevered observation wheel giving breathtaking 360-degree vistas stretching up to 40km across London.",
      tags: ["Sightseeing", "Panoramic", "Thames"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "11:00 - 18:00",
      bestTimeToVisit: "Golden Hour"
    },
    {
      id: "ldn-buckingham",
      name: "Buckingham Palace Changing of the Guard",
      category: "History",
      rating: 4.6,
      price: 0,
      location: "Westminster, SW1A 1AA",
      description: "Official administrative headquarters of the British monarch, famous for the King's Guard ceremonial changing ceremony and The Mall.",
      tags: ["History", "Royalty", "Ceremony"],
      image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:45 Ceremony (Select Days)",
      bestTimeToVisit: "10:30 AM"
    },
    {
      id: "ldn-borough-market",
      name: "Borough Market Artisan Street Food & Cheeses",
      category: "Food",
      rating: 4.9,
      price: 1200,
      location: "8 Southwark St, SE1 1TL",
      description: "London's oldest food market dating to 1014, packed with gourmet mushroom risottos, artisanal cheeses, oysters, and chocolate strawberries.",
      tags: ["Food", "Street Eats", "Gourmet"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00 (Tue-Sun)",
      bestTimeToVisit: "Lunch"
    },
    {
      id: "ldn-westminster-abbey",
      name: "Westminster Abbey Royal Chapels & Poets Corner",
      category: "History",
      rating: 4.8,
      price: 2700,
      location: "Dean's Yard, SW1P 3PA",
      description: "Gothic church that has hosted 40 British coronations since 1066, royal weddings, and the tombs of monarchs and literary icons.",
      tags: ["History", "Architecture", "Royalty"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:30 - 15:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ldn-covent-garden",
      name: "Covent Garden Apple Market & Street Performers",
      category: "Culture",
      rating: 4.7,
      price: 0,
      location: "Covent Garden Piazza, WC2E 8RF",
      description: "Pedestrianized Italianate piazza filled with world-class buskers, independent craft stalls, antique markets, and open-air cafes.",
      tags: ["Culture", "Shopping", "Entertainment"],
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 20:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "ldn-hyde-park",
      name: "Hyde Park Serpentine Boating & Kensington Gardens",
      category: "Nature",
      rating: 4.7,
      price: 0,
      location: "Central London, W2 2UH",
      description: "350-acre Royal Park with pedal boating on Serpentine Lake, Diana Memorial Fountain, and Kensington Palace grounds.",
      tags: ["Nature", "Walks", "Relaxed"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "05:00 - 00:00",
      bestTimeToVisit: "Sunny Afternoon"
    },
    {
      id: "ldn-sky-garden",
      name: "Sky Garden 360 Observation Deck at 20 Fenchurch",
      category: "Sightseeing",
      rating: 4.8,
      price: 0,
      location: "1 Sky Garden Walk, EC3M 8AF",
      description: "Enclosed glass dome on the 35th floor featuring landscaped sub-tropical public gardens, open-air terrace, and sweeping city views.",
      tags: ["Sightseeing", "Panoramic", "Free Entry"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 18:00 (Advance Booking)",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "ldn-afternoon-tea",
      name: "Traditional English Afternoon Tea Experience",
      category: "Food",
      rating: 4.9,
      price: 4500,
      location: "Mayfair / Fortnum & Mason",
      description: "Classic British tea service with warm scones, Cornish clotted cream, strawberry jam, finger sandwiches, and rare tea infusions.",
      tags: ["Food", "Luxury", "Traditional"],
      image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
      openingHours: "13:00 - 17:30",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "ldn-tate-modern",
      name: "Tate Modern & Turbine Hall Contemporary Art",
      category: "Culture",
      rating: 4.7,
      price: 0,
      location: "Bankside, SE1 9TG",
      description: "Converted Bankside Power Station hosting cutting-edge modern art exhibitions by Picasso, Warhol, and Dalí with free rooftop views.",
      tags: ["Culture", "Art", "Free Entry"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 18:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "ldn-camden-market",
      name: "Camden Lock Market Vintage & Alternative Culture",
      category: "Shopping",
      rating: 4.6,
      price: 0,
      location: "Camden Lock Place, NW1 8AF",
      description: "Bohemian labyrinth of lock-side vintage clothes, music memorabilia, eccentric gothic fashion, and international food stalls.",
      tags: ["Shopping", "Culture", "Nightlife"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 19:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "ldn-st-pauls",
      name: "St Paul's Cathedral & Whispering Gallery Dome",
      category: "History",
      rating: 4.8,
      price: 2300,
      location: "St. Paul's Churchyard, EC4M 8AD",
      description: "Sir Christopher Wren's 17th-century masterpiece with its recognizable dome, Whispering Gallery acoustics, and Golden Gallery panorama.",
      tags: ["History", "Architecture", "Panoramic"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:30 - 16:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ldn-greenwich",
      name: "Greenwich Royal Observatory & Prime Meridian",
      category: "Sightseeing",
      rating: 4.7,
      price: 1800,
      location: "Blackheath Ave, SE10 8XJ",
      description: "Stand with one foot in the eastern hemisphere and one in the western across the historic Prime Meridian line (Longitude 0°).",
      tags: ["Sightseeing", "Science", "History"],
      image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "ldn-dishoom",
      name: "Dishoom Bombay Cafe & House Black Daal",
      category: "Food",
      rating: 4.9,
      price: 1600,
      location: "Covent Garden / Shoreditch",
      description: "Nostalgic Irani cafe homage famous for 24-hour slow-cooked creamy Black Daal, gunpowder potatoes, and ruby chicken curry.",
      tags: ["Food", "Iconic", "Culinary"],
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 23:00",
      bestTimeToVisit: "Dinner"
    }
  ],

  "new-york": [
    {
      id: "nyc-liberty",
      name: "Statue of Liberty & Ellis Island Ferry Tour",
      category: "History",
      rating: 4.8,
      price: 2400,
      location: "New York Harbor / Battery Park",
      description: "Iconic copper colossal statue gifted by France in 1886, paired with immigration museum walkthroughs on historic Ellis Island.",
      tags: ["History", "Iconic", "Boating"],
      image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 16:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "nyc-central-park",
      name: "Central Park Bow Bridge & Bethesda Terrace",
      category: "Nature",
      rating: 4.9,
      price: 0,
      location: "59th to 110th St, Manhattan",
      description: "843-acre urban masterpiece designed by Olmsted, featuring rowboats on the Lake, Strawberry Fields John Lennon memorial, and Ramble trails.",
      tags: ["Nature", "Iconic", "Walks"],
      image: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:00 - 01:00",
      bestTimeToVisit: "Sunny Afternoon"
    },
    {
      id: "nyc-empire-state",
      name: "Empire State Building 86th Floor Open Deck",
      category: "Sightseeing",
      rating: 4.7,
      price: 4400,
      location: "20 W 34th St, Midtown",
      description: "Legendary 102-story Art Deco skyscraper with open-air 360-degree observation deck offering dizzying perspectives over Manhattan.",
      tags: ["Sightseeing", "Architecture", "Panoramic"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 00:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "nyc-met-museum",
      name: "Metropolitan Museum of Art (The Met) 5th Ave",
      category: "Culture",
      rating: 4.9,
      price: 2800,
      location: "1000 Fifth Avenue, Upper East Side",
      description: "One of the world's greatest museums housing over two million works including Egyptian Temple of Dendur and European masterpieces.",
      tags: ["Culture", "Art", "History"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:00",
      bestTimeToVisit: "Late Morning"
    },
    {
      id: "nyc-times-square",
      name: "Times Square Neon Spectacular & Broadway",
      category: "Sightseeing",
      rating: 4.6,
      price: 0,
      location: "Broadway & 7th Ave, Midtown",
      description: "The 'Crossroads of the World' blazing with towering digital LED billboards, street buskers, red stairs, and world-famous Broadway theaters.",
      tags: ["Sightseeing", "Nightlife", "Iconic"],
      image: "https://images.unsplash.com/photo-1508873696983-2df5703bc20d?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Night"
    },
    {
      id: "nyc-brooklyn-bridge",
      name: "Brooklyn Bridge Iconic Sunset Walkway",
      category: "Sightseeing",
      rating: 4.8,
      price: 0,
      location: "East River Crossing",
      description: "Pioneering 1883 hybrid cable-stayed suspension bridge with elevated pedestrian wooden promenade and skyline vistas.",
      tags: ["Sightseeing", "Architecture", "Sunset"],
      image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset to Dusk"
    },
    {
      id: "nyc-highline",
      name: "The High Line Elevated Rail Park & Chelsea Market",
      category: "Nature",
      rating: 4.8,
      price: 0,
      location: "Gansevoort St to 34th St",
      description: "1.45-mile public park built on a historic elevated freight rail line above the streets on Manhattan's West Side, adjacent to artisan food hall.",
      tags: ["Nature", "Food", "Architecture"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 22:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "nyc-911-memorial",
      name: "9/11 Memorial Pools & One World Observatory",
      category: "History",
      rating: 4.9,
      price: 3600,
      location: "180 Greenwich St, Financial District",
      description: "Reflecting absence waterfall pools in the footprints of the Twin Towers and the 102nd-floor observation deck of Freedom Tower.",
      tags: ["History", "Panoramic", "Emotional"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 20:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "nyc-grand-central",
      name: "Grand Central Terminal & Whispering Gallery",
      category: "Sightseeing",
      rating: 4.7,
      price: 0,
      location: "89 E 42nd St, Midtown",
      description: "Beaux-Arts transportation cathedral featuring celestial ceiling constellations, four-sided opal clock, and acoustic whispering arches.",
      tags: ["Sightseeing", "Architecture", "History"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "05:15 - 02:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "nyc-joes-pizza",
      name: "Joe's Pizza Greenwich Village Classic Slice",
      category: "Food",
      rating: 4.9,
      price: 450,
      location: "7 Carmine St, Greenwich Village",
      description: "Quintessential New York thin-crust fold-over pizza slice topped with sweet tomato sauce and gooey melted mozzarella since 1975.",
      tags: ["Food", "Iconic", "Street Eats"],
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 04:00",
      bestTimeToVisit: "Lunch & Late Night"
    },
    {
      id: "nyc-greenwich-jazz",
      name: "Greenwich Village Brownstones & Blue Note Jazz",
      category: "Culture",
      rating: 4.8,
      price: 1800,
      location: "Greenwich Village, W 3rd St",
      description: "Historic tree-lined bohemian neighborhood famous for Washington Square Park arch and intimate live jazz performances at Blue Note.",
      tags: ["Culture", "Nightlife", "Music"],
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      openingHours: "18:00 - 01:00",
      bestTimeToVisit: "Evening Jazz"
    },
    {
      id: "nyc-summit-vanderbilt",
      name: "SUMMIT One Vanderbilt Mirror Immersion Deck",
      category: "Sightseeing",
      rating: 4.8,
      price: 4200,
      location: "45 E 42nd St",
      description: "Multi-sensory observation experience 1,200 feet high with infinite mirrored reflection rooms and glass sky boxes cantilevered over Madison Ave.",
      tags: ["Sightseeing", "Modern", "Photography"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 00:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "nyc-soho-shops",
      name: "SoHo Cast-Iron Architecture & Boutiques",
      category: "Shopping",
      rating: 4.7,
      price: 0,
      location: "Broadway, Prince & Spring St",
      description: "Belgian cobblestone streets lined with the world's largest concentration of ornate cast-iron buildings and luxury fashion boutiques.",
      tags: ["Shopping", "Architecture", "Fashion"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "11:00 - 20:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "nyc-natural-history",
      name: "American Museum of Natural History (AMNH)",
      category: "Culture",
      rating: 4.8,
      price: 2500,
      location: "200 Central Park West",
      description: "Immense halls featuring towering T-Rex fossil skeletons, the 94-foot blue whale model, and Hayden Planetarium space shows.",
      tags: ["Culture", "Science", "Family"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 17:30",
      bestTimeToVisit: "Morning"
    },
    {
      id: "nyc-katz-delicatessen",
      name: "Katz's Delicatessen Legendary Pastrami on Rye",
      category: "Food",
      rating: 4.8,
      price: 2400,
      location: "205 E Houston St, Lower East Side",
      description: "No-frills Jewish deli carving thick-cut, house-cured pastrami and corned beef sandwiches with mustard and kosher dill pickles since 1888.",
      tags: ["Food", "Iconic", "Culinary"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 23:00",
      bestTimeToVisit: "Lunch"
    },
    {
      id: "nyc-staten-ferry",
      name: "Staten Island Ferry Manhattan Skyline Cruise",
      category: "Sightseeing",
      rating: 4.7,
      price: 0,
      location: "Whitehall Terminal, Battery Park",
      description: "Free 25-minute commuter boat ride across New York Harbor offering sensational panoramas of Lower Manhattan skyscrapers and Lady Liberty.",
      tags: ["Sightseeing", "Free Entry", "Boating"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset"
    }
  ],

  rome: [
    {
      id: "rom-colosseum",
      name: "Colosseum Arena Floor & Underground Chambers",
      category: "History",
      rating: 4.9,
      price: 2200,
      location: "Piazza del Colosseo, 1",
      description: "Flavian Amphitheatre completed in 80 AD, where 50,000 spectators once witnessed gladiator battles and wild animal spectacles.",
      tags: ["History", "Architecture", "Iconic"],
      image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 16:30",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "rom-vatican",
      name: "Vatican Museums & Sistine Chapel Frescoes",
      category: "Culture",
      rating: 4.9,
      price: 2800,
      location: "Viale Vaticano, 00165",
      description: "Papal palace galleries culminating in Michelangelo's breathtaking ceiling and The Last Judgment in the Sistine Chapel.",
      tags: ["Culture", "Art", "Royalty"],
      image: "https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 18:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "rom-pantheon",
      name: "Pantheon Ancient Roman Dome & Oculus",
      category: "History",
      rating: 4.8,
      price: 500,
      location: "Piazza della Rotonda",
      description: "Best-preserved Roman monument featuring the world's largest unreinforced concrete dome with an open central sunlit oculus.",
      tags: ["History", "Architecture", "Spiritual"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 19:00",
      bestTimeToVisit: "Midday (Sun Beam)"
    },
    {
      id: "rom-trevi",
      name: "Trevi Fountain Coin Toss & Baroque Splendor",
      category: "Sightseeing",
      rating: 4.8,
      price: 0,
      location: "Piazza di Trevi",
      description: "Monumental Baroque fountain depicting Oceanus; tradition dictates tossing a coin with your right hand over left shoulder to guarantee return to Rome.",
      tags: ["Sightseeing", "Art", "Night View"],
      image: "https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Late Night or Sunrise"
    },
    {
      id: "rom-forum",
      name: "Roman Forum & Palatine Hill Imperial Palaces",
      category: "History",
      rating: 4.8,
      price: 1800,
      location: "Via della Salara Vecchia",
      description: "The beating civic, legal, and political heart of the ancient Roman Empire, surrounded by triumphal arches and temples.",
      tags: ["History", "Archaeology", "Walks"],
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 17:00",
      bestTimeToVisit: "Late Afternoon"
    },
    {
      id: "rom-piazza-navona",
      name: "Piazza Navona Bernini Fountains & Open Artists",
      category: "Culture",
      rating: 4.7,
      price: 0,
      location: "Piazza Navona",
      description: "Elegant elliptical square built on Stadium of Domitian, featuring Bernini's Fontana dei Quattro Fiumi and Baroque church Sant'Agnese.",
      tags: ["Culture", "Art", "Architecture"],
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Evening"
    },
    {
      id: "rom-spanish-steps",
      name: "Spanish Steps & Trinità dei Monti Vista",
      category: "Sightseeing",
      rating: 4.7,
      price: 0,
      location: "Piazza di Spagna",
      description: "Monumental 135-step stairway connecting Piazza di Spagna with Trinità dei Monti church and Keats-Shelley House.",
      tags: ["Sightseeing", "Photography", "Historic"],
      image: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "rom-trastevere-dinner",
      name: "Trastevere Alleys & Authentic Roman Trattoria",
      category: "Food",
      rating: 4.9,
      price: 1500,
      location: "Trastevere Quarter",
      description: "Atmospheric ivy-draped cobblestone alleys serving piping hot Cacio e Pepe, crispy Carbonara, and carafes of Castelli Romani wine.",
      tags: ["Food", "Nightlife", "Authentic"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "19:00 - 00:00",
      bestTimeToVisit: "Dinner"
    },
    {
      id: "rom-campo-fiori",
      name: "Campo de' Fiori Morning Farmers Market",
      category: "Food",
      rating: 4.6,
      price: 0,
      location: "Piazza Campo de' Fiori",
      description: "Vibrant medieval square hosting bustling morning stalls with sun-ripened tomatoes, Sicilian olive oils, aged balsamic, and warm pizza bianca.",
      tags: ["Food", "Shopping", "Local Culture"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 14:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "rom-borghese",
      name: "Borghese Gallery & Villa Borghese Gardens",
      category: "Culture",
      rating: 4.9,
      price: 2100,
      location: "Piazzale Scipione Borghese, 5",
      description: "Opulent villa museum displaying breathtaking Bernini marble sculptures (Apollo and Daphne) and Caravaggio oil paintings.",
      tags: ["Culture", "Art", "Gardens"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 19:00 (Advance Booking)",
      bestTimeToVisit: "Morning"
    },
    {
      id: "rom-castel-santangelo",
      name: "Castel Sant'Angelo Fortress & Tiber River View",
      category: "History",
      rating: 4.7,
      price: 1400,
      location: "Lungotevere Castello, 50",
      description: "Emperor Hadrian's cylindrical mausoleum later converted into a papal fortress with fortified escape corridors to the Vatican.",
      tags: ["History", "Architecture", "Sunset"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 19:30",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "rom-giolitti",
      name: "Giolitti Historic Artisanal Gelateria",
      category: "Food",
      rating: 4.9,
      price: 350,
      location: "Via Uffici del Vicario, 40",
      description: "Rome's most storied ice cream salon established in 1890, celebrated for pistachio di Bronte, dark chocolate, and panna fresca.",
      tags: ["Food", "Dessert", "Iconic"],
      image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:30 - 01:00",
      bestTimeToVisit: "Afternoon & Night"
    },
    {
      id: "rom-appian-way",
      name: "Appian Way Ancient Roman Cobblestone Hike",
      category: "Adventure",
      rating: 4.7,
      price: 0,
      location: "Via Appia Antica",
      description: "Walk or cycle along the 'Queen of Long Roads' on original 2,300-year-old basalt flagstones flanked by ancient pines and catacombs.",
      tags: ["Adventure", "History", "Nature"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Morning Bike Ride"
    },
    {
      id: "rom-altare-patria",
      name: "Altare della Patria Victor Emmanuel Monument",
      category: "Sightseeing",
      rating: 4.6,
      price: 0,
      location: "Piazza Venezia",
      description: "Colossal white Brescian marble monument dedicated to unified Italy's first king, featuring glass elevators to Rome's highest roof panorama.",
      tags: ["Sightseeing", "History", "Panoramic"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:30 - 19:30",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "rom-janiculum",
      name: "Janiculum Hill Noon Cannon & Skyline Vista",
      category: "Sightseeing",
      rating: 4.7,
      price: 0,
      location: "Gianicolo, Trastevere",
      description: "Promontory above western Rome offering arguably the finest sunset perspective over all the domes and campaniles in the eternal city.",
      tags: ["Sightseeing", "Sunset", "Romantic"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "rom-terme-caracalla",
      name: "Baths of Caracalla Ancient Imperial Spa Ruins",
      category: "History",
      rating: 4.7,
      price: 800,
      location: "Viale delle Terme di Caracalla, 52",
      description: "Vast remains of second-century Roman public bathhouses that once accommodated 1,600 bathers with Olympic swimming pools.",
      tags: ["History", "Architecture", "Archaeology"],
      image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 16:30",
      bestTimeToVisit: "Morning"
    }
  ],

  "kuala-lumpur": [
    {
      id: "kl-petronas",
      name: "Petronas Twin Towers Skybridge & 86th Deck",
      category: "Sightseeing",
      rating: 4.9,
      price: 1600,
      location: "Kuala Lumpur City Centre",
      description: "452-meter post-modern Islamic skyscrapers linked by a double-decker skybridge 170 meters in the air.",
      tags: ["Sightseeing", "Architecture", "Iconic"],
      image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 21:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "kl-batu-caves",
      name: "Batu Caves Rainbow Steps & Murugan Statue",
      category: "Culture",
      rating: 4.8,
      price: 0,
      location: "Gombak, Selangor",
      description: "Vast limestone cave temples guarded by a 140-foot golden Lord Murugan statue reached via 272 brightly painted rainbow steps.",
      tags: ["Culture", "Adventure", "Spiritual"],
      image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 21:00",
      bestTimeToVisit: "Early Morning"
    },
    {
      id: "kl-jalan-alor",
      name: "Jalan Alor Bustling Night Food Street",
      category: "Food",
      rating: 4.8,
      price: 400,
      location: "Bukit Bintang",
      description: "Vibrant culinary street lined with open-air plastic tables serving grilled chicken wings, spicy satay, durian, and dim sum.",
      tags: ["Food", "Street Eats", "Nightlife"],
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      openingHours: "17:00 - 02:00",
      bestTimeToVisit: "Night Food Trail"
    },
    {
      id: "kl-klcc-park",
      name: "KLCC Park Lake Symphony Fountain Show",
      category: "Nature",
      rating: 4.7,
      price: 0,
      location: "Jalan Ampang",
      description: "50-acre tropical green park directly beneath the Petronas Towers with nightly choreographed musical water fountains.",
      tags: ["Nature", "Night Show", "Relaxed"],
      image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 22:00",
      bestTimeToVisit: "Evening Fountain Show"
    },
    {
      id: "kl-thean-hou",
      name: "Thean Hou Temple Six-Tier Chinese Shrine",
      category: "Culture",
      rating: 4.8,
      price: 0,
      location: "Lorong Bellamy, Robson Heights",
      description: "Spectacular multi-tiered Chinese temple blending Buddhism, Taoism, and Confucianism adorned with thousands of red lanterns.",
      tags: ["Culture", "Architecture", "Photography"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "08:00 - 22:00",
      bestTimeToVisit: "Late Afternoon & Dusk"
    },
    {
      id: "kl-tower",
      name: "KL Tower Observation Deck & Sky Box",
      category: "Sightseeing",
      rating: 4.6,
      price: 1200,
      location: "Bukit Nanas",
      description: "Telecommunications tower perched on pineapple hill with an open-air Sky Deck and glass-bottomed Sky Box protruding into thin air.",
      tags: ["Sightseeing", "Panoramic", "Adventure"],
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 22:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "kl-bukit-bintang",
      name: "Bukit Bintang Pavilion Shopping & Boutiques",
      category: "Shopping",
      rating: 4.7,
      price: 0,
      location: "Bukit Bintang",
      description: "Premier shopping and entertainment precinct packed with mega-malls, rooftop bistros, and international flagship stores.",
      tags: ["Shopping", "Modern", "Fashion"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 22:00",
      bestTimeToVisit: "Afternoon & Evening"
    },
    {
      id: "kl-merdeka",
      name: "Merdeka Square & Sultan Abdul Samad Moorish Hall",
      category: "History",
      rating: 4.6,
      price: 0,
      location: "City Centre",
      description: "Birthplace of Malaysian independence featuring a 95m flagpole, cricket green, and 19th-century copper-domed colonial architecture.",
      tags: ["History", "Architecture", "Heritage"],
      image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
      openingHours: "24 Hours",
      bestTimeToVisit: "Morning or Night"
    },
    {
      id: "kl-botanical",
      name: "Perdana Botanical Gardens & Orchid Sanctuary",
      category: "Nature",
      rating: 4.6,
      price: 0,
      location: "Jalan Kebun Bunga",
      description: "220-acre landscaped heritage park featuring a sunken garden, deer sanctuary, and thousands of tropical orchid varieties.",
      tags: ["Nature", "Flowers", "Relaxed"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
      openingHours: "07:00 - 20:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "kl-central-market",
      name: "Central Market (Pasar Seni) Cultural Souvenirs",
      category: "Shopping",
      rating: 4.6,
      price: 0,
      location: "Jalan Hang Kasturi",
      description: "Art Deco heritage market established in 1888 showcasing Malaysian pewter, batik prints, wood carvings, and shadow puppets.",
      tags: ["Shopping", "Culture", "Handicrafts"],
      image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 20:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "kl-nasi-lemak",
      name: "Village Park Restaurant Authentic Nasi Lemak",
      category: "Food",
      rating: 4.9,
      price: 250,
      location: "Damansara Utama",
      description: "Malaysia's most acclaimed breakfast spot serving fragrant coconut rice, crispy fried spiced chicken, sambal, and roasted peanuts.",
      tags: ["Food", "Iconic", "Culinary"],
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
      openingHours: "06:30 - 17:30",
      bestTimeToVisit: "Morning Breakfast"
    },
    {
      id: "kl-islamic-arts",
      name: "Islamic Arts Museum Southeast Asia",
      category: "Culture",
      rating: 4.8,
      price: 250,
      location: "Jalan Lembah, Tasik Perdana",
      description: "Exquisite museum housing scale models of world mosques, intricate Quranic manuscripts, jewelry, and glazed ceramics.",
      tags: ["Culture", "Art", "Architecture"],
      image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:30 - 18:00",
      bestTimeToVisit: "Morning"
    },
    {
      id: "kl-aquaria",
      name: "Aquaria KLCC Oceanarium Tunnel",
      category: "Adventure",
      rating: 4.6,
      price: 1100,
      location: "Concourse Level, KL Convention Centre",
      description: "60,000-square-foot oceanarium featuring a 90-meter underwater tunnel with tiger sharks, giant stingrays, and sea turtles.",
      tags: ["Adventure", "Marine", "Family"],
      image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 20:00",
      bestTimeToVisit: "Afternoon"
    },
    {
      id: "kl-chinatown",
      name: "Petaling Street Chinatown Flea Market",
      category: "Culture",
      rating: 4.6,
      price: 0,
      location: "Jalan Petaling",
      description: "Covered night bazaar under a green dragon roof selling herbal teas, roast duck, and bargain souvenirs in historic shop houses.",
      tags: ["Culture", "Shopping", "Food"],
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      openingHours: "10:00 - 22:00",
      bestTimeToVisit: "Evening"
    },
    {
      id: "kl-heli-lounge",
      name: "Heli Lounge Bar Rooftop Helipad Sunset",
      category: "Sightseeing",
      rating: 4.7,
      price: 600,
      location: "Menara KH, Jalan Sultan Ismail",
      description: "Fully functioning daytime helicopter landing pad transformed by evening into an unrailed 360-degree open-air cocktail terrace.",
      tags: ["Sightseeing", "Nightlife", "Sunset"],
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
      openingHours: "17:00 - 01:00",
      bestTimeToVisit: "Sunset"
    },
    {
      id: "kl-masjid-negara",
      name: "National Mosque of Malaysia (Masjid Negara)",
      category: "Culture",
      rating: 4.7,
      price: 0,
      location: "Jalan Perdana",
      description: "Striking 1965 modern Islamic structure with a 16-pointed star concrete main roof resembling an open umbrella and 73m minaret.",
      tags: ["Culture", "Architecture", "Spiritual"],
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
      openingHours: "09:00 - 18:00 (Non-prayer times)",
      bestTimeToVisit: "Morning"
    }
  ]
};

module.exports = { EXPANDED };
